# Generated by Django 4.2.1 on 2023-05-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.AddField(
            model_name='vote',
            name='user_ip',
            field=models.TextField(default='0.0.0.0', max_length='12'),
        ),
    ]
